# This is the default format.
# For more see: http://jekyllrb.com/docs/permalinks/
permalink: /:categories/:title

markdown: kramdown

exclude: [".rvmrc", ".rbenv-version", "README.md",
  "Rakefile", "changelog.md", "sandbox",
  "node_modules", "gulpfile.js", ".editorconfig",
  "assets/components/*", "bower.json"
]

# Themes are encouraged to use these universal variables
# so be sure to set them if your theme uses them.
title : "SKGTech"
email: hello@skgtech.io
description: "The community of developers, designers and techies who live in Thessaloniki"
author :
  name : "SKGTech Contributors"
  email : "skg-developers@googlegroups.com"
  github : "skgtech"
  twitter : SKG_Tech
  # feedburner : feedname
githubrepo: "https://github.com/skgtech/skgtech.github.io"

# The production_url is only used when full-domain names are needed
# such as sitemap.txt
# Most places will/should use BASE_PATH to make the urls
#
# If you have set a CNAME (pages.github.com) set your custom domain here.
# Else if you are pushing to username.github.io, replace with your username.
# Finally if you are pushing to a GitHub project page, include the project name at the end.
#
production_url : http://skgtech.io

# Open Graph data
og:
  app_id: "698696243515776"
  title: "Thessaloniki tech Community"
  site_name: "SKGTech"
  image: "http://skgtech.io/assets/img/skgtech-social-logo.png"

# Google Analytics
analytics :
  provider : google
  google :
    tracking_id : 'UA-41787746-3'
    domain: 'skgtech.io'
